[package]
name = "deezer"
version = "0.1.0"
authors = ["Max JoÌˆhnk <maxjoehnk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
thiserror = "1"
async-trait = "0.1"

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-core", "macros"] }